---
- name: Basic Install SLURM on the cluster nodes
  hosts: cluster
  roles:
      - marvel-nccr.slurm

- name: Slurm setup on the nodes
  become: true
  hosts: nodes
  tags: finalsetup
  tasks:
      - name: Copy the munge key from master to the nodes
        synchronize: 
            src: "{{ item }}"
            dest: "{{ item }}"
            mode: push
        delegate_to: master.local
        with_items:
            - "/etc/munge/munge.key"
        notify:
            - Restart munge on nodes
      - name : Set up slurm.conf
        copy:
            src: templates/slurm.conf
            dest: /etc/slurm-llnl/slurm.conf
            mode: 0644
            owner: root
            group: root
        notify:
            - Restart slurmd/slurmctld
  handlers:
      - name: Restart munge on nodes
        service:
            name: "{{ item }}"
            state: restarted
        with_items:
            - munge
      - name: Restart slurmd/slurmctld
        service:
            name: "slurmd"
            state: restarted
        service:
            name: "slurmctld"
            state: stopped

- name: Slurm setup on the master
  become: true
  hosts: master
  tags: finalsetup
  tasks:
      - name : Set up slurm.conf
        copy:
            src: templates/slurm.conf
            dest: /etc/slurm-llnl/slurm.conf
            mode: 0644
            owner: root
            group: root
        notify:
            - Restart slurmd/slurmctld
  handlers:
      - name: Restart slurmd/slurmctld
        service:
            name: "slurmd"
            state: stopped
        service:
            name: "slurmctld"
            state: restarted


- name: Open ondemand
  hosts: master
  roles:
      - ood.ansible
