---
- name: Basic Install SLURM on the cluster nodes
  hosts: cluster
  roles:
      - marvel-nccr.slurm

- name: Slurm setup on the cluster
  become: true
  hosts: nodes
  tags: finalsetup
  tasks:
      - name: Copy the munge key from master to the nodes
        synchronize: 
            src: "{{ item }}"
            dest: "{{ item }}"
            mode: push
        delegate_to: master.local
        with_items:
            - "/etc/munge/munge.key"
        notify:
            - Restart munge on nodes
      - name : Configure slurm
        copy:
            src: templates/slurm.conf
            dest: /etc/slurm-llnl/slurm.conf
            mode: 0644
            owner: root
            group: root

  handlers:
      - name: Restart munge on nodes
        service:
            name: "{{ item }}"
            state: restarted
        with_items:
            - munge

- name: Clean up slurmctl and slurmd on nodes
  become: true
  hosts: nodes
  tasks:
      - name: slurmd running on nodes
        service:
            name: "slurmd"
            state: started
      - name: slurmctld stopped on nodes
        service:
            name: "slurmctld"
            state: stopped

- name: Clean up slurmctl and slurmd on master
  become: true
  hosts: master
  tasks:
      - name: slurmd stopped on master
        service:
            name: "slurmd"
            state: stopped
      - name: slurmctld started on master
        service:
            name: "slurmd"
            state: started


# - hosts: cluster
#   become: true
#   tasks:
#       - name : Configure slurm
#         template:
#             src: templates/slurm.conf.j2
#             dest: /etc/slurm-llnl/slurm.conf
#             mode: 0640
#             owner: root
#             group: root
#         notify:
#             - restart slurm

#   handlers:
#       - name: restart slurm
#         service:
#             name: "{{ item }}"
#             state: restarted
#         with_items:
#             - slurmctld
#             - slurmd


