---

# - name: Install head
#   hosts: master
#   apt:
#       pkg: ["munge", "build-essential"]
#       state: latest
#       update_cache: true


- name: Basic Install SLURM on the cluster nodes
  hosts: cluster
  roles:
      - marvel-nccr.slurm

- name: Slurm setup on the cluster
  become: true
  hosts: nodes
  tags: finalsetup
  tasks:
      - name: Copy the munge key from master to the nodes
        synchronize: 
            src: "{{ item }}"
            dest: "{{ item }}"
            mode: push
        delegate_to: master.local
        with_items:
            - "/etc/munge/munge.key"
        notify:
            - Restart munge on nodes

  handlers:
      - name: Restart munge on nodes
        service:
            name: "{{ item }}"
            state: restarted
        with_items:
            - munge

# - hosts: cluster
#   become: true
#   tasks:
#       - name : Configure slurm
#         template:
#             src: templates/slurm.conf.j2
#             dest: /etc/slurm-llnl/slurm.conf
#             mode: 0640
#             owner: root
#             group: root
#         notify:
#             - restart slurm

#   handlers:
#       - name: restart slurm
#         service:
#             name: "{{ item }}"
#             state: restarted
#         with_items:
#             - slurmctld
#             - slurmd


