# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
MASTER_IMAGE = "hashicorp/bionic64"
NODE_IMAGE = "hashicorp/bionic64"
NODE_COUNT = 4

$hostscript = <<-SCRIPT
cp /etc/hosts /root && \
echo '192.168.50.2 master' >> /etc/hosts
echo '192.168.50.3 node1' >> /etc/hosts
echo '192.168.50.4 node2' >> /etc/hosts
echo '192.168.50.5 node3' >> /etc/hosts
echo '192.168.50.6 node4' >> /etc/hosts
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.define "master" do |master|
		master.vm.box = MASTER_IMAGE
		master.vm.hostname = "master"
		master.vm.network "private_network", ip:"192.168.50.2"
		# Install avahi to allow to ping the nodes 
		master.vm.provision "shell", inline: <<-SHELL
			apt update --quiet
			apt install -y --quiet avahi-daemon avahi-utils libnss-mdns
		SHELL

		master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		master.vm.provision "shell", :inline =>
		"cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false
		# Copy the password less ssh key for root
		private_key = File.read("id_rsa")
		master.vm.provision "shell", :inline => "
			mkdir -p ~/.ssh
			echo '#{private_key}' >> ~/.ssh/id_rsa
		", privileged: true
		# Make the hosts file
		master.vm.provision "shell", inline: $hostscript
	end

	(1..NODE_COUNT).each do |i|
		config.vm.define "node#{i}" do |node|
			node.vm.box = NODE_IMAGE
			node.vm.hostname = "node#{i}"
			node.vm.network "private_network", ip:"192.168.50.#{i+2}"
			# Install avahi to allow to ping the nodes 
			node.vm.provision "shell", inline: <<-SHELL
				apt update --quiet
				apt install -y --quiet avahi-daemon avahi-utils libnss-mdns
			SHELL

			node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
			node.vm.provision "shell", :inline =>
			"cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys", privileged: false
			# Copy the public key on the nodes
			public_key = File.read("id_rsa.pub")
			node.vm.provision :shell, :inline => "
				mkdir -p ~/.ssh
				echo '#{public_key}' >> ~/.ssh/authorized_keys
			", privileged: true
			# Make the hosts file
			node.vm.provision "shell", inline: $hostscript
		end
	end

end
