# Slurm service files

- name: Copy slurmd service file
  copy: src=lib/systemd/system/slurmd.service dest=/lib/systemd/system/slurmd.service owner=root group=root mode=0644
  notify:
    - Start slurmd

- name: Copy slurmd service environment file
  copy: src=etc/default/slurmd dest=/etc/default/slurmd owner=root group=root mode=0644

- name: Create symbolic link to service file
  file:
    src: /lib/systemd/system/slurmd.service
    dest: /etc/systemd/system/multi-user.target.wants/slurmd.service
    owner: root
    group: root
    state: link
  notify:
    - Start slurmd

