- hosts: all
  become: true
  roles:
    - slurm.common
    - slurm
    - singularity.wrapper

- hosts:
    - slurm_master
  become: true
  roles:
    - slurm.master
    - slurm.user

- hosts:
    - compute_nodes    
  become: true
  roles:
    - slurm.compute
    - xfce
    - nomachine

- hosts: 
    - slurm_master
  become: true
  vars:
    - ood_is_server: yes
  roles: 
    - ood.wrapper

- hosts: compute_nodes
  become: true
  vars:
    - ood_is_client: yes
  roles: 
    - ood.wrapper

