- hosts:
    - slurm_hosts
  become: true
  roles:
    - slurm.common
    - slurm

- hosts:
    - slurm_master
  become: true
  roles:
    - slurm.master
    - slurm.user

- hosts:
    - compute_nodes    
  become: true
  roles:
      - slurm.compute
      - xfce
      - nomachine

 - hosts: slurm_master
   become: true
   roles: 
       - {role:odd-wrapper, ood_is_server: yes}

 - hosts: compute_nodes
   become: true
   roles: 
       - {role:odd-wrapper, ood_is_client: yes}

- hosts: all
  become: true
  roles: 
    - singularity_wrapper
