---
ood_source_version: "v2.0.9"
ood_config_dir: /etc/ood/config
ood_base_dir: /opt/ood

# Cluster configuration
ood_cluster_config_dir: '{{ ood_config_dir }}/clusters.d'
ood_cluster_title: "Slurm demo cluster"
ood_cluster_name: "democluster"         # has to match Slurm cluster name
ood_default_password: "deepops"

# OOD front page config
ood_frontpage_config : |
  pun_custom_env:
    OOD_DASHBOARD_TITLE: "Slurm demo cluster"
    OOD_BRAND_BG_COLOR: "#76B900"
    OOD_BRAND_LINK_ACTIVE_BG_COLOR: "#333"
    OOD_NAVBAR_TYPE: "inverse"

ood_is_server: no
ood_is_client: no
