# Create slurm group and user

- name: Ensure group 'slurm' exists with correct gid
  group:
    name: slurm
    state: present
    gid: 64030

- name: Ensure user 'slurm' exists with correct uid
  user:
    name: slurm
    state: present
    uid: 64030
    group: slurm
    home: /home/slurm
    shell: /bin/sh

# Create munge group and user

- name: Ensure group 'munge' exists with correct gid
  group:
    name: munge
    state: present
    gid: 900

- name: Ensure user 'munge' exists with correct uid
  user:
    name: munge
    state: present
    uid: 900
    group: munge
    home: /nonexistent
    shell: /usr/sbin/nologin
  notify:
    - Restart munge

# Install and configure munge

- name: Install munge
  apt:
    name: munge
    state: present
  notify:
    - Restart munge

- name: Copy munge key
  copy: src=etc/munge/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0400
  notify:
    - Restart munge

- name: Change file ownership and group of munge dir
  file:
    path: "{{ item }}"
    owner: munge
    group: munge
    recurse: yes
  notify:
    - Restart munge
  loop:
    - /etc/munge
    - /var/log/munge
    - /var/lib/munge
    - /run/munge

# Install slurm prerequisites

- name: Create /opt/slurm dir
  file:
    path: /opt/slurm
    state: directory
    mode: '0755'

- name: Install dependencies
  apt:
    pkg:
      - libhwloc-dev
    state: present
    update_cache: true

- name: Copy libhwloc-dev .deb package to /opt/slurm
  copy: src=/opt/ansible/sources/libhwloc5_1.11.9-1_amd64.deb dest=/opt/slurm/libhwloc5_1.11.9-1_amd64.deb owner=root group=root mode=0644

- name: Install libhwloc .deb package
  apt:
    deb: /opt/slurm/libhwloc5_1.11.9-1_amd64.deb

# Install slurm binaries

- name: Copy slurm .deb package to /opt/slurm
  copy: src=/opt/ansible/sources/slurm_20.02.3-1_amd64.deb dest=/opt/slurm/slurm_20.02.3-1_amd64.deb owner=root group=root mode=0644
  when: ansible_distribution_version == "20.04"

- name: Install slurm .deb package
  apt:
    deb: /opt/slurm/slurm_20.02.3-1_amd64.deb

# Slurm configuration

- name: Remove slurm-llnl directories if they exist
  file:
    path: "{{ item }}"
    state: absent
    mode: '0755'
  loop:
    - /etc/slurm-llnl
    - /var/log/slurm-llnl
    - /var/spool/slurm-llnl
    - /var/run/slurm-llnl

- name: Create slurm directories if they do not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/slurm
    - /var/log/slurm
    - /var/spool/slurm
    - /var/run/slurm

- name: Copy slurm cgroup configuration file
  copy: src=etc/slurm/cgroup.conf dest=/etc/slurm/cgroup.conf owner=root group=root mode=0644

- name: Copy slurm gres configuration file
  copy: src=etc/slurm/gres.conf dest=/etc/slurm/gres.conf owner=root group=root mode=0644

